require('dotenv').config();
const mongoose = require('mongoose');
const {
  getGeneratedResume,
  getGeneratedJoiningLetter,
  shouldGenerateJoiningLetter,
} = require('./utils/studentDocuments');

async function seed() {
  const uri = process.env.MONGO_URI || 'mongodb://localhost:27017/placement_portal';
  await mongoose.connect(uri);
  console.log('✅ Connected to MongoDB\n');

  const User        = require('./models/User');
  const Student     = require('./models/Student');
  const Job         = require('./models/Job');
  const Internship  = require('./models/Internship');
  const Application = require('./models/Application');

  // ═══════════════════════════════════════
  //  1. ADMIN
  // ═══════════════════════════════════════
  let adminUser = await User.findOne({ email: 'admin@placement.edu' });
  if (!adminUser) {
    adminUser = await User.create({ name:'Placement Admin', email:'admin@placement.edu', password:'admin123', role:'admin', isActive:true, isEmailVerified:true });
    console.log('✅ Admin created  → admin@placement.edu / admin123');
  } else {
    console.log('⚠️  Admin exists  → admin@placement.edu');
  }

  // ═══════════════════════════════════════
  //  2. STUDENTS (30)
  // ═══════════════════════════════════════
  const studentsData = [
    // B.Tech CSE
    { name:'Aarav Sharma',     email:'aarav.sharma01@gmail.com',     phone:'9876501001', gender:'Male',   dob:'2002-04-15', address:'14 Shivaji Nagar, Pune, Maharashtra 411005',            course:'B.Tech', branch:'CSE',                    sem:7, yr:4, roll:'2021BTCSE001', cgpa:8.9, p10:92.4, p12:88.6, cgpas:[{semester:1,cgpa:8.5},{semester:2,cgpa:8.7},{semester:3,cgpa:8.9},{semester:4,cgpa:9.0},{semester:5,cgpa:9.1},{semester:6,cgpa:8.8},{semester:7,cgpa:8.9}], skills:['React','Node.js','Python','AWS','MongoDB'],                li:'linkedin.com/in/aarav-sharma',        gh:'github.com/aarav-sharma',   ps:'Placed',     pa:'Google India',        pkg:24, is:'Completed', ic:'Infosys',            id:'6 months', ist:25000, bio:'Full-stack developer passionate about scalable systems.' },
    { name:'Priya Patel',      email:'priya.patel22@gmail.com',      phone:'9876501002', gender:'Female', dob:'2002-08-22', address:'7 Satellite Road, Ahmedabad, Gujarat 380015',           course:'B.Tech', branch:'CSE',                    sem:7, yr:4, roll:'2021BTCSE002', cgpa:9.2, p10:95.0, p12:93.2, cgpas:[{semester:1,cgpa:9.0},{semester:2,cgpa:9.2},{semester:3,cgpa:9.3},{semester:4,cgpa:9.4},{semester:5,cgpa:9.1},{semester:6,cgpa:9.2},{semester:7,cgpa:9.2}], skills:['Java','Spring Boot','SQL','Azure','Docker'],             li:'linkedin.com/in/priya-patel-cse',     gh:'github.com/priya-patel',    ps:'Placed',     pa:'Microsoft India',     pkg:28, is:'Completed', ic:'TCS',                id:'6 months', ist:20000, bio:'Backend engineer with deep Java and enterprise expertise.' },
    { name:'Rohan Verma',      email:'rohan.verma03@gmail.com',      phone:'9876501003', gender:'Male',   dob:'2003-01-10', address:'22 MG Road, Bengaluru, Karnataka 560001',               course:'B.Tech', branch:'CSE',                    sem:5, yr:3, roll:'2022BTCSE003', cgpa:7.8, p10:85.2, p12:82.0, cgpas:[{semester:1,cgpa:7.5},{semester:2,cgpa:7.8},{semester:3,cgpa:7.9},{semester:4,cgpa:7.7},{semester:5,cgpa:7.8}],                              skills:['C++','Data Structures','Machine Learning','OpenCV'],     li:'linkedin.com/in/rohan-verma-dev',     gh:'github.com/rohan-verma',    ps:'In Process',               pkg:0,  is:'Ongoing',  ic:'Wipro',              id:'3 months', ist:15000, bio:'Competitive programmer focused on DSA and ML.' },
    { name:'Sneha Gupta',      email:'sneha.gupta04@gmail.com',      phone:'9876501004', gender:'Female', dob:'2004-06-03', address:'5 Rajouri Garden, New Delhi 110027',                    course:'B.Tech', branch:'CSE',                    sem:3, yr:2, roll:'2023BTCSE004', cgpa:8.4, p10:90.0, p12:87.4, cgpas:[{semester:1,cgpa:8.2},{semester:2,cgpa:8.5},{semester:3,cgpa:8.4}],                                                                              skills:['Python','Django','HTML/CSS','JavaScript','PostgreSQL'],  li:'linkedin.com/in/sneha-gupta-dev',     gh:'github.com/sneha-gupta',    ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Web developer with a keen interest in UI/UX and Python backends.' },
    // B.Tech ECE
    { name:'Karan Mehta',      email:'karan.mehta05@gmail.com',      phone:'9876501005', gender:'Male',   dob:'2002-11-28', address:'33 Salt Lake Sector V, Kolkata, West Bengal 700091',    course:'B.Tech', branch:'ECE',                    sem:7, yr:4, roll:'2021BTECE001', cgpa:8.1, p10:88.0, p12:84.5, cgpas:[{semester:1,cgpa:7.8},{semester:2,cgpa:8.0},{semester:3,cgpa:8.2},{semester:4,cgpa:8.3},{semester:5,cgpa:8.1},{semester:6,cgpa:8.0},{semester:7,cgpa:8.1}], skills:['VLSI','Embedded C','IoT','MATLAB','Verilog'],            li:'linkedin.com/in/karan-mehta-ece',     gh:'github.com/karan-mehta',    ps:'Placed',     pa:'Samsung R&D',         pkg:18, is:'Completed', ic:'BSNL',               id:'2 months', ist:12000, bio:'VLSI design enthusiast with extensive IoT project experience.' },
    { name:'Divya Singh',      email:'divya.singh06@gmail.com',      phone:'9876501006', gender:'Female', dob:'2003-03-17', address:'8 Indira Nagar, Lucknow, Uttar Pradesh 226016',         course:'B.Tech', branch:'ECE',                    sem:5, yr:3, roll:'2022BTECE002', cgpa:7.5, p10:82.4, p12:79.2, cgpas:[{semester:1,cgpa:7.2},{semester:2,cgpa:7.5},{semester:3,cgpa:7.6},{semester:4,cgpa:7.4},{semester:5,cgpa:7.5}],                              skills:['Circuit Design','Arduino','Python','Signal Processing'],  li:'linkedin.com/in/divya-singh-ece',     gh:'',                          ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Electronics student passionate about embedded systems and IoT.' },
    // B.Tech Mechanical
    { name:'Arjun Nair',       email:'arjun.nair07@gmail.com',       phone:'9876501007', gender:'Male',   dob:'2002-07-05', address:'12 Pattom Road, Thiruvananthapuram, Kerala 695004',     course:'B.Tech', branch:'Mechanical Engineering', sem:7, yr:4, roll:'2021BTME001',  cgpa:7.9, p10:86.2, p12:83.0, cgpas:[{semester:1,cgpa:7.5},{semester:2,cgpa:7.8},{semester:3,cgpa:8.0},{semester:4,cgpa:7.9},{semester:5,cgpa:7.8},{semester:6,cgpa:7.7},{semester:7,cgpa:7.9}], skills:['AutoCAD','SolidWorks','ANSYS','Pro-E','GD&T'],           li:'linkedin.com/in/arjun-nair-mech',     gh:'',                          ps:'Placed',     pa:'Tata Motors',         pkg:12, is:'Completed', ic:'L&T',                id:'3 months', ist:10000, bio:'Mechanical engineer specialising in automotive design.' },
    { name:'Meera Joshi',      email:'meera.joshi08@gmail.com',      phone:'9876501008', gender:'Female', dob:'2003-09-14', address:'19 Tilak Nagar, Nashik, Maharashtra 422001',            course:'B.Tech', branch:'Mechanical Engineering', sem:5, yr:3, roll:'2022BTME002',  cgpa:6.8, p10:78.6, p12:76.0, cgpas:[{semester:1,cgpa:6.5},{semester:2,cgpa:6.8},{semester:3,cgpa:6.9},{semester:4,cgpa:6.7},{semester:5,cgpa:6.8}],                              skills:['Thermodynamics','CAD','Manufacturing','CATIA'],          li:'linkedin.com/in/meera-joshi-mech',    gh:'',                          ps:'Not Placed',               pkg:0,  is:'Ongoing',  ic:'Bosch India',        id:'6 months', ist:14000, bio:'Interested in thermal engineering and sustainable manufacturing.' },
    // B.Tech Civil
    { name:'Yash Kulkarni',    email:'yash.kulkarni09@gmail.com',    phone:'9876501009', gender:'Male',   dob:'2002-02-20', address:'45 Deccan Gymkhana, Pune, Maharashtra 411004',          course:'B.Tech', branch:'Civil Engineering',      sem:7, yr:4, roll:'2021BTCVL001', cgpa:7.4, p10:81.0, p12:78.4, cgpas:[{semester:1,cgpa:7.1},{semester:2,cgpa:7.3},{semester:3,cgpa:7.5},{semester:4,cgpa:7.4},{semester:5,cgpa:7.4},{semester:6,cgpa:7.3},{semester:7,cgpa:7.4}], skills:['AutoCAD','STAAD Pro','Primavera','Project Management'],  li:'linkedin.com/in/yash-kulkarni-civil',  gh:'',                          ps:'Not Placed',               pkg:0,  is:'Completed', ic:'DLF Group',          id:'2 months', ist:8000,  bio:'Civil engineer with expertise in structural analysis and planning.' },
    { name:'Swati Jain',       email:'swati.jain10@gmail.com',       phone:'9876501010', gender:'Female', dob:'2003-12-01', address:'3 Banjara Hills Road 10, Hyderabad, Telangana 500034',  course:'B.Tech', branch:'Civil Engineering',      sem:5, yr:3, roll:'2022BTCVL002', cgpa:8.1, p10:88.4, p12:86.0, cgpas:[{semester:1,cgpa:7.9},{semester:2,cgpa:8.0},{semester:3,cgpa:8.2},{semester:4,cgpa:8.1},{semester:5,cgpa:8.1}],                              skills:['Revit','AutoCAD Civil 3D','GIS','Construction Management'],li:'linkedin.com/in/swati-jain-civil',    gh:'',                          ps:'In Process',               pkg:0,  is:'Completed', ic:'Shapoorji Pallonji', id:'3 months', ist:9000,  bio:'Passionate about smart infrastructure and sustainable construction.' },
    // M.Tech
    { name:'Rahul Iyer',       email:'rahul.iyer11@gmail.com',       phone:'9876501011', gender:'Male',   dob:'2000-05-18', address:'67 Anna Nagar West, Chennai, Tamil Nadu 600040',        course:'M.Tech', branch:'CSE',                    sem:3, yr:2, roll:'2023MTCSE001', cgpa:8.7, p10:92.0, p12:90.2, cgpas:[{semester:1,cgpa:8.5},{semester:2,cgpa:8.8},{semester:3,cgpa:8.7}],                                                                              skills:['ML','Deep Learning','TensorFlow','Python','Scala','Spark'],li:'linkedin.com/in/rahul-iyer-ml',      gh:'github.com/rahul-iyer',     ps:'Placed',     pa:'Amazon India',        pkg:35, is:'Completed', ic:'Adobe Systems',      id:'6 months', ist:50000, bio:'AI/ML researcher with publications in NLP and distributed systems.' },
    { name:'Kavya Reddy',      email:'kavya.reddy12@gmail.com',      phone:'9876501012', gender:'Female', dob:'2001-10-07', address:'28 Jubilee Hills Road 36, Hyderabad, Telangana 500033', course:'M.Tech', branch:'AI & Machine Learning',  sem:1, yr:1, roll:'2024MTAI001',  cgpa:9.0, p10:96.4, p12:94.0, cgpas:[{semester:1,cgpa:9.0}],                                                                                                                        skills:['NLP','Computer Vision','PyTorch','R','Hugging Face'],    li:'linkedin.com/in/kavya-reddy-ai',      gh:'github.com/kavya-reddy',    ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Passionate about conversational AI and generative models.' },
    { name:'Ritika Saxena',    email:'ritika.saxena13@gmail.com',    phone:'9876501013', gender:'Female', dob:'2000-08-25', address:'11 Koramangala 5th Block, Bengaluru, Karnataka 560095', course:'M.Tech', branch:'Data Engineering',       sem:3, yr:2, roll:'2023MTDE001',  cgpa:8.4, p10:91.2, p12:89.0, cgpas:[{semester:1,cgpa:8.2},{semester:2,cgpa:8.5},{semester:3,cgpa:8.4}],                                                                              skills:['Kafka','Spark','Airflow','dbt','Python','Snowflake'],    li:'linkedin.com/in/ritika-saxena-de',    gh:'github.com/ritika-saxena',  ps:'Placed',     pa:'Uber India',          pkg:30, is:'Completed', ic:'PhonePe',            id:'6 months', ist:40000, bio:'Data engineer building real-time pipelines for financial domains.' },
    // BCA
    { name:'Siddharth Kumar',  email:'siddharth.kumar14@gmail.com',  phone:'9876501014', gender:'Male',   dob:'2002-03-30', address:'9 Hazratganj, Lucknow, Uttar Pradesh 226001',           course:'BCA',    branch:'Computer Applications', sem:5, yr:3, roll:'2022BCA001',    cgpa:7.6, p10:84.0, p12:81.6, cgpas:[{semester:1,cgpa:7.3},{semester:2,cgpa:7.5},{semester:3,cgpa:7.7},{semester:4,cgpa:7.6},{semester:5,cgpa:7.6}],                              skills:['PHP','MySQL','JavaScript','WordPress','Laravel'],        li:'linkedin.com/in/siddharth-kumar-bca', gh:'github.com/siddharth-kumar',ps:'In Process',               pkg:0,  is:'Completed', ic:'HCL Technologies',   id:'3 months', ist:12000, bio:'Full-stack web developer with strong PHP backend skills.' },
    { name:'Pooja Agarwal',    email:'pooja.agarwal15@gmail.com',    phone:'9876501015', gender:'Female', dob:'2003-07-12', address:'16 Civil Lines, Jaipur, Rajasthan 302006',              course:'BCA',    branch:'Computer Applications', sem:3, yr:2, roll:'2023BCA002',    cgpa:8.0, p10:88.6, p12:86.4, cgpas:[{semester:1,cgpa:7.8},{semester:2,cgpa:8.0},{semester:3,cgpa:8.0}],                                                                              skills:['React','CSS','Figma','UI/UX','Tailwind CSS'],            li:'linkedin.com/in/pooja-agarwal-design', gh:'github.com/pooja-agarwal', ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'UI/UX designer and frontend dev focused on accessible interfaces.' },
    { name:'Nikhil Chauhan',   email:'nikhil.chauhan16@gmail.com',   phone:'9876501016', gender:'Male',   dob:'2002-11-05', address:'24 Rohini Sector 3, New Delhi 110085',                  course:'BCA',    branch:'Computer Applications', sem:5, yr:3, roll:'2022BCA003',    cgpa:6.9, p10:76.2, p12:74.0, cgpas:[{semester:1,cgpa:6.7},{semester:2,cgpa:6.9},{semester:3,cgpa:7.0},{semester:4,cgpa:6.8},{semester:5,cgpa:6.9}],                              skills:['Python','Flask','MongoDB','REST APIs'],                  li:'linkedin.com/in/nikhil-chauhan-dev',   gh:'',                          ps:'Not Placed',               pkg:0,  is:'Ongoing',  ic:'Zoho Corporation',   id:'6 months', ist:15000, bio:'Backend developer building lightweight APIs and automation tools.' },
    // MCA
    { name:'Ananya Mishra',    email:'ananya.mishra17@gmail.com',    phone:'9876501017', gender:'Female', dob:'2001-04-09', address:'6 Arera Colony, Bhopal, Madhya Pradesh 462016',         course:'MCA',    branch:'Computer Applications', sem:3, yr:2, roll:'2023MCA001',    cgpa:8.5, p10:91.4, p12:89.2, cgpas:[{semester:1,cgpa:8.3},{semester:2,cgpa:8.5},{semester:3,cgpa:8.5}],                                                                              skills:['Java','Angular','Spring','Oracle DB','Microservices'],  li:'linkedin.com/in/ananya-mishra-java',  gh:'github.com/ananya-mishra',  ps:'Placed',     pa:'Cognizant',           pkg:16, is:'Completed', ic:'Mphasis',            id:'6 months', ist:20000, bio:'Enterprise Java developer with hands-on microservices experience.' },
    { name:'Varun Tiwari',     email:'varun.tiwari18@gmail.com',     phone:'9876501018', gender:'Male',   dob:'2002-09-21', address:'31 Shastri Nagar, Kanpur, Uttar Pradesh 208005',        course:'MCA',    branch:'Computer Applications', sem:1, yr:1, roll:'2024MCA002',    cgpa:7.4, p10:80.2, p12:77.4, cgpas:[{semester:1,cgpa:7.4}],                                                                                                                        skills:['C#','.NET','SQL Server','ASP.NET MVC'],                 li:'linkedin.com/in/varun-tiwari-dotnet',  gh:'',                          ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'.NET developer exploring enterprise application development.' },
    // BBA
    { name:'Ishaan Kapoor',    email:'ishaan.kapoor19@gmail.com',    phone:'9876501019', gender:'Male',   dob:'2002-06-14', address:'55 Defence Colony, New Delhi 110024',                   course:'BBA',    branch:'Marketing',             sem:5, yr:3, roll:'2022BBAMKT001', cgpa:7.8, p10:85.4, p12:83.0, cgpas:[{semester:1,cgpa:7.5},{semester:2,cgpa:7.7},{semester:3,cgpa:7.9},{semester:4,cgpa:7.8},{semester:5,cgpa:7.8}],                              skills:['Digital Marketing','SEO','Google Analytics','Excel','Canva'],li:'linkedin.com/in/ishaan-kapoor-mkt', gh:'',                          ps:'Placed',     pa:'Hindustan Unilever',  pkg:8,  is:'Completed', ic:'P&G India',          id:'2 months', ist:18000, bio:'Marketing enthusiast focused on brand strategy and digital campaigns.' },
    { name:'Riya Bansal',      email:'riya.bansal20@gmail.com',      phone:'9876501020', gender:'Female', dob:'2002-12-28', address:'18 Model Town, Ludhiana, Punjab 141002',                 course:'BBA',    branch:'Finance',               sem:5, yr:3, roll:'2022BBAFIN001', cgpa:8.2, p10:89.6, p12:87.2, cgpas:[{semester:1,cgpa:8.0},{semester:2,cgpa:8.1},{semester:3,cgpa:8.3},{semester:4,cgpa:8.2},{semester:5,cgpa:8.2}],                              skills:['Financial Analysis','Tally ERP','Excel','Python','Financial Modelling'],li:'linkedin.com/in/riya-bansal-finance',gh:'',                          ps:'In Process',               pkg:0,  is:'Completed', ic:'HDFC Bank',          id:'2 months', ist:15000, bio:'Finance major interested in investment banking and equity research.' },
    { name:'Aditya Rao',       email:'aditya.rao21@gmail.com',       phone:'9876501021', gender:'Male',   dob:'2003-05-06', address:'2 Jayanagar 4th Block, Bengaluru, Karnataka 560011',    course:'BBA',    branch:'Human Resources',       sem:3, yr:2, roll:'2023BBAHR001',  cgpa:7.3, p10:79.4, p12:76.6, cgpas:[{semester:1,cgpa:7.0},{semester:2,cgpa:7.3},{semester:3,cgpa:7.3}],                                                                              skills:['HR Management','Communication','MS Office','Recruitment'],li:'linkedin.com/in/aditya-rao-hr',      gh:'',                          ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'HR student interested in organisational behaviour and talent acquisition.' },
    { name:'Manish Trivedi',   email:'manish.trivedi22@gmail.com',   phone:'9876501022', gender:'Male',   dob:'2002-10-19', address:'40 Paldi, Ahmedabad, Gujarat 380007',                   course:'BBA',    branch:'International Business',sem:5, yr:3, roll:'2022BBAIB001',  cgpa:7.7, p10:84.2, p12:82.0, cgpas:[{semester:1,cgpa:7.5},{semester:2,cgpa:7.7},{semester:3,cgpa:7.8},{semester:4,cgpa:7.6},{semester:5,cgpa:7.7}],                              skills:['Import/Export','Forex','International Trade','Supply Chain'],li:'linkedin.com/in/manish-trivedi-ib', gh:'',                          ps:'Not Placed',               pkg:0,  is:'Ongoing',  ic:'Reliance Industries',id:'6 months', ist:16000, bio:'Aspiring global trade professional with EXIM policy expertise.' },
    // MBA
    { name:'Shruti Malhotra',  email:'shruti.malhotra23@gmail.com',  phone:'9876501023', gender:'Female', dob:'1999-07-11', address:'77 Punjabi Bagh West, New Delhi 110026',                course:'MBA',    branch:'Operations Management', sem:3, yr:2, roll:'2023MBAOPS001', cgpa:8.6, p10:93.4, p12:91.2, cgpas:[{semester:1,cgpa:8.5},{semester:2,cgpa:8.7},{semester:3,cgpa:8.6}],                                                                              skills:['Supply Chain','Six Sigma','Power BI','Tableau','SAP SCM'],li:'linkedin.com/in/shruti-malhotra-ops',gh:'',                          ps:'Placed',     pa:'McKinsey & Company',  pkg:32, is:'Completed', ic:'Deloitte Consulting', id:'3 months', ist:60000, bio:'Operations consultant with Six Sigma Green Belt certification.' },
    { name:'Vivek Saxena',     email:'vivek.saxena24@gmail.com',     phone:'9876501024', gender:'Male',   dob:'2000-02-23', address:'13 Saket, New Delhi 110017',                            course:'MBA',    branch:'Marketing',             sem:1, yr:1, roll:'2024MBAMKT001', cgpa:7.9, p10:86.0, p12:84.2, cgpas:[{semester:1,cgpa:7.9}],                                                                                                                        skills:['Brand Management','Consumer Research','Digital Marketing'],li:'linkedin.com/in/vivek-saxena-mba',   gh:'',                          ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'MBA student with prior startup experience in D2C brand building.' },
    { name:'Preeti Desai',     email:'preeti.desai25@gmail.com',     phone:'9876501025', gender:'Female', dob:'1999-09-16', address:'4 Malabar Hill, Mumbai, Maharashtra 400006',            course:'MBA',    branch:'Finance',               sem:3, yr:2, roll:'2023MBAFIN001', cgpa:8.9, p10:94.2, p12:92.4, cgpas:[{semester:1,cgpa:8.8},{semester:2,cgpa:9.0},{semester:3,cgpa:8.9}],                                                                              skills:['Investment Banking','Valuation','Bloomberg','Excel VBA','DCF Modelling'],li:'linkedin.com/in/preeti-desai-finance',gh:'',                        ps:'Placed',     pa:'Goldman Sachs India', pkg:38, is:'Completed', ic:'JP Morgan Chase',     id:'3 months', ist:75000, bio:'Finance professional with expertise in capital markets.' },
    // B.Sc
    { name:'Harsh Pandey',     email:'harsh.pandey26@gmail.com',     phone:'9876501026', gender:'Male',   dob:'2003-01-27', address:'50 Allahabad Road, Varanasi, Uttar Pradesh 221005',     course:'B.Sc',   branch:'Physics',               sem:5, yr:3, roll:'2022BSCPHY001', cgpa:7.2, p10:82.0, p12:80.4, cgpas:[{semester:1,cgpa:7.0},{semester:2,cgpa:7.1},{semester:3,cgpa:7.3},{semester:4,cgpa:7.2},{semester:5,cgpa:7.2}],                              skills:['Research Methods','MATLAB','COMSOL','LaTeX','Data Analysis'],li:'linkedin.com/in/harsh-pandey-physics',gh:'',                          ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Physics student interested in computational physics and research.' },
    { name:'Tanvi Bose',       email:'tanvi.bose27@gmail.com',       phone:'9876501027', gender:'Female', dob:'2002-04-02', address:'38 Lake Town Block B, Kolkata, West Bengal 700089',     course:'B.Sc',   branch:'Chemistry',             sem:5, yr:3, roll:'2022BSCCHE001', cgpa:8.0, p10:87.6, p12:85.0, cgpas:[{semester:1,cgpa:7.7},{semester:2,cgpa:7.9},{semester:3,cgpa:8.1},{semester:4,cgpa:8.0},{semester:5,cgpa:8.0}],                              skills:['Analytical Chemistry','HPLC','Spectroscopy','GC-MS'],   li:'linkedin.com/in/tanvi-bose-chem',     gh:'',                          ps:'In Process',               pkg:0,  is:'Completed', ic:"Dr. Reddy's Labs",   id:'2 months', ist:10000, bio:'Chemistry graduate with pharmaceutical industry exposure.' },
    { name:'Gaurav Mishra',    email:'gaurav.mishra28@gmail.com',    phone:'9876501028', gender:'Male',   dob:'2003-08-08', address:'21 Tilak Marg, Raipur, Chhattisgarh 492001',            course:'B.Sc',   branch:'Mathematics',           sem:3, yr:2, roll:'2023BSCMAT001', cgpa:8.3, p10:90.4, p12:88.2, cgpas:[{semester:1,cgpa:8.1},{semester:2,cgpa:8.3},{semester:3,cgpa:8.3}],                                                                              skills:['Statistics','R','Python','Data Analysis','Linear Algebra'],li:'linkedin.com/in/gaurav-mishra-math',  gh:'github.com/gaurav-mishra', ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Mathematics student targeting data science with strong stats skills.' },
    // M.Sc
    { name:'Nidhi Agrawal',    email:'nidhi.agrawal29@gmail.com',    phone:'9876501029', gender:'Female', dob:'2001-06-24', address:'62 Hauz Khas Village, New Delhi 110016',                course:'M.Sc',   branch:'Data Science',          sem:3, yr:2, roll:'2023MSCDS001',  cgpa:9.1, p10:95.2, p12:93.4, cgpas:[{semester:1,cgpa:9.0},{semester:2,cgpa:9.2},{semester:3,cgpa:9.1}],                                                                              skills:['Machine Learning','Big Data','Spark','Hadoop','SQL','Tableau'],li:'linkedin.com/in/nidhi-agrawal-ds',  gh:'github.com/nidhi-agrawal',  ps:'Placed',     pa:'Flipkart Analytics',  pkg:22, is:'Completed', ic:'Mu Sigma',           id:'6 months', ist:30000, bio:'Data scientist with expertise in big data and predictive modelling.' },
    { name:'Saurabh Tripathi', email:'saurabh.tripathi30@gmail.com', phone:'9876501030', gender:'Male',   dob:'2002-03-13', address:'10 Niti Bagh, New Delhi 110049',                        course:'M.Sc',   branch:'Physics',               sem:1, yr:1, roll:'2024MSCPHY001', cgpa:7.6, p10:83.4, p12:81.0, cgpas:[{semester:1,cgpa:7.6}],                                                                                                                        skills:['Quantum Mechanics','Computational Physics','MATLAB','Python'],li:'linkedin.com/in/saurabh-tripathi-physics',gh:'',                      ps:'Not Placed',               pkg:0,  is:'Not Done',                           id:'',         ist:0,     bio:'Physics postgraduate exploring quantum computing and simulation.' },
  ];

  let studentDocs = [];
  let created = 0, updated = 0, errors = 0;

  for (const s of studentsData) {
    try {
      let user = await User.findOne({ email: s.email });
      if (!user) {
        user = await User.create({ name:s.name, email:s.email, password:'student123', role:'student', isEmailVerified:true, isActive:true });
      }
      const payload = {
        rollNumber:s.roll, phone:s.phone, gender:s.gender,
        dateOfBirth:new Date(s.dob), address:s.address,
        course:s.course, branch:s.branch, semester:s.sem, year:s.yr,
        cgpa:s.cgpa, semesterCGPAs:s.cgpas,
        percentage10th:s.p10, percentage12th:s.p12,
        skills:s.skills, linkedIn:s.li||'', github:s.gh||'',
        placementStatus:s.ps, placedAt:s.pa||'', packageOffered:s.pkg||0,
        internshipStatus:s.is, internshipCompany:s.ic||'',
        internshipDuration:s.id||'', internshipStipend:s.ist||0,
        resume:getGeneratedResume(s),
        joiningLetter:shouldGenerateJoiningLetter(s) ? getGeneratedJoiningLetter(s) : undefined,
        bio:s.bio, isEligible:true,
      };
      let doc = await Student.findOne({ user:user._id });
      if (doc) {
        doc = await Student.findOneAndUpdate({ user:user._id }, { $set:payload }, { new:true });
        updated++;
      } else {
        doc = await Student.create({ user:user._id, ...payload });
        created++;
      }
      studentDocs.push({ doc, data:s });
      console.log(`${created+updated <= 1?'✅':'  '} ${s.name.padEnd(20)} | ${s.roll} | ${s.email}`);
    } catch(e) { console.error(`❌ ${s.name}: ${e.message}`); errors++; }
  }
  console.log(`\n Students → Created:${created}  Updated:${updated}  Errors:${errors}\n`);

  // ═══════════════════════════════════════
  //  3. JOBS (25)
  // ═══════════════════════════════════════
  await Job.deleteMany({});
  const deadline = (days) => new Date(Date.now() + days * 86400000);
  const jobsData = [
    // ── Original 10 ──
    { title:'Software Engineer – Full Stack', company:'Google India', description:'Build scalable web applications using React and Node.js. Work on consumer-facing products used by millions.', requirements:'Strong DSA skills, React/Node.js experience, problem solving', location:'Bengaluru', jobType:'Full-time', salary:{min:1800000,max:2400000}, eligibility:{minCGPA:7.5,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['React','Node.js','Python','System Design'], applicationDeadline:deadline(30), driveDate:deadline(45), rounds:['Online Test','Technical Round 1','Technical Round 2','HR'], status:'Open' },
    { title:'Data Scientist', company:'Amazon India', description:'Develop ML models for recommendation and search systems. Work with petabyte-scale data.', requirements:'Python, ML frameworks, statistical analysis', location:'Hyderabad', jobType:'Full-time', salary:{min:2000000,max:3500000}, eligibility:{minCGPA:8.0,allowedCourses:['B.Tech','M.Tech','M.Sc'],allowedBranches:['CSE','AI & Machine Learning','Data Science']}, skills:['Python','TensorFlow','Spark','SQL'], applicationDeadline:deadline(20), driveDate:deadline(35), rounds:['Coding Test','ML Case Study','System Design','Bar Raiser'], status:'Open' },
    { title:'Backend Developer – Java', company:'Microsoft India', description:'Design and develop microservices for Azure cloud platform. Own features end to end.', requirements:'Java, Spring Boot, distributed systems, REST APIs', location:'Pune', jobType:'Full-time', salary:{min:1600000,max:2800000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['Java','Spring Boot','Azure','Docker','Kubernetes'], applicationDeadline:deadline(25), driveDate:deadline(40), rounds:['Aptitude','Coding','Technical','Managerial','HR'], status:'Open' },
    { title:'Embedded Systems Engineer', company:'Samsung R&D India', description:'Design firmware and drivers for next-gen mobile chipsets and IoT devices.', requirements:'Embedded C, VLSI, RTOS, microcontrollers', location:'Noida', jobType:'Full-time', salary:{min:1200000,max:1800000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech'],allowedBranches:['ECE','EEE']}, skills:['Embedded C','RTOS','VLSI','IoT','Verilog'], applicationDeadline:deadline(18), driveDate:deadline(30), rounds:['Written Test','Technical Interview','HR'], status:'Open' },
    { title:'Management Consultant', company:'McKinsey & Company', description:'Solve complex business problems for Fortune 500 clients. Lead strategy and operations projects.', requirements:'MBA, strong analytical and communication skills', location:'Mumbai', jobType:'Full-time', salary:{min:2500000,max:3500000}, eligibility:{minCGPA:8.0,allowedCourses:['MBA'],allowedBranches:[]}, skills:['Strategy','Data Analysis','PowerPoint','Case Solving','Excel'], applicationDeadline:deadline(15), driveDate:deadline(28), rounds:['Case Interview 1','Case Interview 2','Fit Interview','Partner Round'], status:'Open' },
    { title:'Investment Banking Analyst', company:'Goldman Sachs India', description:'Support M&A transactions and IPO processes. Build financial models and pitch books for deals.', requirements:'MBA Finance or CFA, strong financial modelling skills', location:'Mumbai', jobType:'Full-time', salary:{min:2000000,max:3800000}, eligibility:{minCGPA:8.0,allowedCourses:['MBA','M.Com'],allowedBranches:['Finance']}, skills:['DCF Modelling','Bloomberg','Excel VBA','Investment Banking','Valuation'], applicationDeadline:deadline(12), driveDate:deadline(22), rounds:['Resume Screen','Technical Test','Three Interview Rounds'], status:'Open' },
    { title:'Data Engineer', company:'Uber India', description:'Build and maintain real-time data pipelines that power Uber\'s marketplace. Work with Kafka, Spark, and Flink at scale.', requirements:'Python, Spark, Kafka, Airflow, SQL', location:'Bengaluru', jobType:'Full-time', salary:{min:1800000,max:3000000}, eligibility:{minCGPA:7.5,allowedCourses:['B.Tech','M.Tech','M.Sc'],allowedBranches:['CSE','Data Science','Data Engineering']}, skills:['Kafka','Spark','Python','Airflow','Snowflake'], applicationDeadline:deadline(22), driveDate:deadline(38), rounds:['Online Coding','System Design','Behavioral','Hiring Manager'], status:'Open' },
    { title:'Structural Design Engineer', company:'Tata Projects', description:'Design and analyse structures for large-scale infrastructure and industrial projects.', requirements:'B.Tech Civil, AutoCAD, STAAD Pro, structural analysis', location:'Chennai', jobType:'Full-time', salary:{min:700000,max:1000000}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech'],allowedBranches:['Civil Engineering']}, skills:['AutoCAD','STAAD Pro','ANSYS','Structural Design'], applicationDeadline:deadline(35), driveDate:deadline(50), rounds:['Aptitude Test','Technical Interview','HR Interview'], status:'Open' },
    { title:'Digital Marketing Manager', company:'Hindustan Unilever', description:'Lead digital campaigns for top FMCG brands. Own SEO, SEM, social media and performance marketing.', requirements:'BBA/MBA Marketing, Google Analytics, Meta Ads experience', location:'Mumbai', jobType:'Full-time', salary:{min:800000,max:1200000}, eligibility:{minCGPA:7.0,allowedCourses:['BBA','MBA'],allowedBranches:['Marketing']}, skills:['Digital Marketing','SEO','Google Analytics','Meta Ads','Canva'], applicationDeadline:deadline(28), driveDate:deadline(42), rounds:['Group Discussion','Personal Interview','HR'], status:'Open' },
    { title:'CAD/CAM Design Engineer', company:'Tata Motors', description:'Design automotive components and assemblies. Perform FEM analysis and GD&T documentation.', requirements:'B.Tech Mechanical, SolidWorks, ANSYS, AutoCAD', location:'Pune', jobType:'Full-time', salary:{min:800000,max:1200000}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech'],allowedBranches:['Mechanical Engineering']}, skills:['SolidWorks','ANSYS','AutoCAD','CATIA','GD&T'], applicationDeadline:deadline(40), driveDate:deadline(55), rounds:['Written Test','Technical Interview','HR'], status:'Open' },
    // ── New 15 ──
    { title:'Machine Learning Engineer', company:'Infosys AI Lab', description:'Develop and deploy production-grade ML pipelines for NLP and computer vision applications across Infosys client projects.', requirements:'Python, PyTorch/TensorFlow, MLOps, REST API deployment', location:'Bengaluru', jobType:'Full-time', salary:{min:1400000,max:2200000}, eligibility:{minCGPA:7.5,allowedCourses:['B.Tech','M.Tech','M.Sc'],allowedBranches:['CSE','AI & Machine Learning','Data Science']}, skills:['Python','PyTorch','MLflow','Docker','FastAPI'], applicationDeadline:deadline(32), driveDate:deadline(48), rounds:['Online Assessment','ML Technical Round','System Design','HR'], status:'Open' },
    { title:'Cloud Solutions Architect', company:'Wipro Technologies', description:'Design cloud-native architectures on AWS and Azure for enterprise digital transformation engagements. Work with Fortune 500 clients globally.', requirements:'AWS/Azure certifications, microservices, IaC with Terraform', location:'Hyderabad', jobType:'Full-time', salary:{min:1500000,max:2600000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['AWS','Azure','Terraform','Kubernetes','CI/CD'], applicationDeadline:deadline(27), driveDate:deadline(42), rounds:['Aptitude','Cloud Technical','Architecture Case','HR'], status:'Open' },
    { title:'VLSI Design Engineer', company:'Qualcomm India', description:'Design and verify digital RTL blocks for Snapdragon SoC product lines. Contribute to chip tape-out cycles.', requirements:'B.Tech/M.Tech ECE, Verilog/VHDL, Synopsys tools, UVM', location:'Hyderabad', jobType:'Full-time', salary:{min:1600000,max:2400000}, eligibility:{minCGPA:7.5,allowedCourses:['B.Tech','M.Tech'],allowedBranches:['ECE','EEE']}, skills:['Verilog','VHDL','Synopsys','UVM','RTL Design'], applicationDeadline:deadline(21), driveDate:deadline(36), rounds:['Written Test','VLSI Technical Round 1','VLSI Technical Round 2','HR'], status:'Open' },
    { title:'Product Manager – SaaS', company:'Zoho Corporation', description:'Own the product roadmap for Zoho CRM modules. Work with engineering, design, and sales to ship features loved by 1M+ users.', requirements:'MBA/B.Tech, 0–2 yrs product experience, analytical mindset', location:'Chennai', jobType:'Full-time', salary:{min:1000000,max:1600000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MBA'],allowedBranches:['CSE','Marketing']}, skills:['Product Strategy','SQL','Figma','Agile','User Research'], applicationDeadline:deadline(19), driveDate:deadline(34), rounds:['Product Case','Metrics Round','Leadership Interview','HR'], status:'Open' },
    { title:'Equity Research Analyst', company:'HDFC Securities', description:'Produce buy/sell/hold reports on mid-cap and large-cap equities. Present actionable investment ideas to fund managers.', requirements:'MBA Finance or CFA Level 1, financial modelling, Bloomberg', location:'Mumbai', jobType:'Full-time', salary:{min:900000,max:1400000}, eligibility:{minCGPA:7.5,allowedCourses:['MBA','M.Com'],allowedBranches:['Finance']}, skills:['Financial Modelling','Bloomberg','Equity Valuation','PowerPoint','Excel VBA'], applicationDeadline:deadline(14), driveDate:deadline(26), rounds:['Written Test','Model Review','Interview','HR'], status:'Open' },
    { title:'DevOps Engineer', company:'Razorpay', description:'Build and maintain CI/CD pipelines and observability infrastructure for Razorpay\'s payments platform handling 10M+ transactions/day.', requirements:'Linux, Docker, Kubernetes, Jenkins, Prometheus/Grafana', location:'Bengaluru', jobType:'Full-time', salary:{min:1400000,max:2200000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['Kubernetes','Docker','Jenkins','Prometheus','Grafana','Python'], applicationDeadline:deadline(24), driveDate:deadline(39), rounds:['Online Coding','DevOps Technical','System Design','HR'], status:'Open' },
    { title:'HR Business Partner', company:'Cognizant', description:'Partner with business units to drive talent strategy, performance management, and employee engagement for a 5000-member delivery unit.', requirements:'MBA HR or equivalent, HR generalist experience, communication skills', location:'Pune', jobType:'Full-time', salary:{min:700000,max:1100000}, eligibility:{minCGPA:6.5,allowedCourses:['MBA','MCA','BBA'],allowedBranches:['Human Resources']}, skills:['HR Management','Talent Acquisition','HRMS','Communication','Conflict Resolution'], applicationDeadline:deadline(26), driveDate:deadline(41), rounds:['Group Discussion','HR Interview','Senior Leadership Interview'], status:'Open' },
    { title:'Thermal & Fluids Engineer', company:'L&T Engineering', description:'Perform CFD analysis and thermal simulation for heavy industrial equipment including turbines, heat exchangers, and pressure vessels.', requirements:'B.Tech/M.Tech Mechanical, ANSYS Fluent, thermodynamics', location:'Mumbai', jobType:'Full-time', salary:{min:750000,max:1100000}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech','M.Tech'],allowedBranches:['Mechanical Engineering']}, skills:['ANSYS Fluent','CFD','Thermodynamics','SolidWorks','MATLAB'], applicationDeadline:deadline(38), driveDate:deadline(53), rounds:['Written Test','Technical Interview','HR Interview'], status:'Open' },
    { title:'Android Developer', company:'PhonePe', description:'Build high-performance Android features for PhonePe\'s 500M+ user payments super-app. Own features from design to release.', requirements:'Kotlin, Android SDK, MVVM, Jetpack Compose, REST APIs', location:'Bengaluru', jobType:'Full-time', salary:{min:1600000,max:2600000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['Kotlin','Android SDK','Jetpack Compose','MVVM','Firebase'], applicationDeadline:deadline(17), driveDate:deadline(32), rounds:['Online Coding','Android Technical','System Design','HR'], status:'Open' },
    { title:'Geotechnical Engineer', company:'Shapoorji Pallonji', description:'Conduct soil investigations, foundation design, and slope stability analysis for real estate and infrastructure mega-projects across India.', requirements:'B.Tech Civil, geotechnical analysis, PLAXIS/GeoStudio', location:'Mumbai', jobType:'Full-time', salary:{min:650000,max:950000}, eligibility:{minCGPA:6.0,allowedCourses:['B.Tech'],allowedBranches:['Civil Engineering']}, skills:['PLAXIS','GeoStudio','AutoCAD','Geotechnical Analysis','Report Writing'], applicationDeadline:deadline(45), driveDate:deadline(60), rounds:['Written Test','Technical Interview','HR Interview'], status:'Open' },
    { title:'Supply Chain Analyst', company:'Reliance Retail', description:'Optimise inventory levels, vendor lead times, and last-mile logistics across Reliance\'s 18,000+ store network using advanced analytics.', requirements:'MBA Operations or equivalent, Excel, SAP, supply chain analytics', location:'Mumbai', jobType:'Full-time', salary:{min:900000,max:1400000}, eligibility:{minCGPA:7.0,allowedCourses:['MBA','BBA'],allowedBranches:['Operations Management','International Business']}, skills:['Supply Chain','SAP SCM','Excel','Power BI','Inventory Management'], applicationDeadline:deadline(29), driveDate:deadline(44), rounds:['Aptitude Test','Case Study','Personal Interview','HR'], status:'Open' },
    { title:'Cybersecurity Analyst', company:'HCL Technologies', description:'Monitor SOC alerts, conduct vulnerability assessments, and respond to security incidents for HCL\'s global enterprise clients.', requirements:'B.Tech CSE/IT, CEH/CompTIA Security+, SIEM tools, network security', location:'Noida', jobType:'Full-time', salary:{min:900000,max:1500000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','MCA'],allowedBranches:['CSE','IT']}, skills:['SIEM','Penetration Testing','Network Security','Python','Incident Response'], applicationDeadline:deadline(23), driveDate:deadline(37), rounds:['Aptitude','Technical Security Round','Scenario-Based Interview','HR'], status:'Open' },
    { title:'Quality Assurance Engineer', company:'Mphasis', description:'Design and execute automated test suites for banking and insurance software products. Own QA strategy for agile delivery teams.', requirements:'Selenium, TestNG, Java, API testing with Postman/RestAssured', location:'Bengaluru', jobType:'Full-time', salary:{min:800000,max:1300000}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech','M.Tech','MCA','BCA'],allowedBranches:['CSE','IT','Computer Applications']}, skills:['Selenium','Java','TestNG','Postman','JIRA','Agile'], applicationDeadline:deadline(31), driveDate:deadline(46), rounds:['Online Test','Technical Interview','HR Interview'], status:'Open' },
    { title:'R&D Physicist – Instrumentation', company:'ISRO (Guest Faculty Channel)', description:'Develop and calibrate scientific instruments for satellite payloads. Contribute to data acquisition systems for earth observation missions.', requirements:'M.Sc/M.Tech Physics or ECE, MATLAB, signal processing, LabVIEW', location:'Bengaluru', jobType:'Full-time', salary:{min:700000,max:1000000}, eligibility:{minCGPA:7.5,allowedCourses:['M.Sc','M.Tech','B.Tech'],allowedBranches:['Physics','ECE']}, skills:['MATLAB','LabVIEW','Signal Processing','Python','Instrumentation'], applicationDeadline:deadline(36), driveDate:deadline(52), rounds:['Written Test','Technical Interview','Document Verification'], status:'Open' },
    { title:'Business Analyst – Fintech', company:'Paytm', description:'Bridge product and engineering to define user stories, analyse payment funnels, and drive data-backed decisions for Paytm\'s lending business.', requirements:'B.Tech/MBA, SQL, data analysis, product thinking, stakeholder management', location:'Noida', jobType:'Full-time', salary:{min:1000000,max:1600000}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','MBA','M.Sc'],allowedBranches:['CSE','Finance','Data Science']}, skills:['SQL','Excel','Tableau','Agile','Product Analytics'], applicationDeadline:deadline(16), driveDate:deadline(30), rounds:['Case Study','SQL Test','Stakeholder Interview','HR'], status:'Open' },
  ];

  const createdJobs = await Job.insertMany(jobsData.map(j => ({ ...j, postedBy:adminUser._id })));
  console.log(`✅ ${createdJobs.length} Jobs created (10 original + 15 new)\n`);

  // ═══════════════════════════════════════
  //  4. INTERNSHIPS (20)
  // ═══════════════════════════════════════
  await Internship.deleteMany({});
  const internshipsData = [
    // ── Original 5 ──
    { title:'Software Development Intern', company:'Google India', description:'Work alongside senior engineers on real product features in Google Search or Google Pay. Mentored internship with PPO opportunity.', requirements:'Strong coding skills in Python or Java, DSA proficiency', location:'Bengaluru', mode:'On-site', duration:'6 months', stipend:{amount:60000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.5,allowedCourses:['B.Tech','M.Tech','MCA'],minSemester:5,maxSemester:8}, skills:['Python','Java','DSA','System Design'], applicationDeadline:deadline(20), startDate:deadline(45), isPPO:true, status:'Open' },
    { title:'Data Science Intern', company:'Flipkart', description:'Analyse buyer behaviour data to build recommendation models. Work with petabyte-scale datasets and state-of-the-art ML pipelines.', requirements:'Python, ML basics, SQL, statistics', location:'Bengaluru', mode:'Hybrid', duration:'6 months', stipend:{amount:35000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech','M.Sc'],minSemester:3,maxSemester:8}, skills:['Python','Pandas','SQL','Machine Learning','Tableau'], applicationDeadline:deadline(15), startDate:deadline(35), isPPO:true, status:'Open' },
    { title:'Finance & Investments Intern', company:'JP Morgan Chase', description:'Support the Equity Research team with financial modelling, sector research and client presentations.', requirements:'MBA Finance, Excel, financial analysis', location:'Mumbai', mode:'On-site', duration:'3 months', stipend:{amount:75000,currency:'INR',period:'month'}, eligibility:{minCGPA:8.0,allowedCourses:['MBA'],minSemester:1,maxSemester:4}, skills:['Excel VBA','Bloomberg','DCF Modelling','PowerPoint'], applicationDeadline:deadline(10), startDate:deadline(25), isPPO:false, status:'Open' },
    { title:'Embedded Systems Intern', company:'Bosch India', description:'Develop firmware for automotive ECUs and IoT sensors. Work with AUTOSAR and CAN bus protocols.', requirements:'Embedded C, microcontrollers, RTOS basics', location:'Pune', mode:'On-site', duration:'6 months', stipend:{amount:18000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech'],minSemester:5,maxSemester:8}, skills:['Embedded C','AUTOSAR','CAN Bus','MATLAB','Simulink'], applicationDeadline:deadline(25), startDate:deadline(50), isPPO:false, status:'Open' },
    { title:'Marketing & Brand Intern', company:'P&G India', description:'Assist brand teams with campaign planning, market research and consumer insight projects across leading FMCG brands.', requirements:'BBA/MBA Marketing, analytical mindset, communication skills', location:'Mumbai', mode:'On-site', duration:'2 months', stipend:{amount:20000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['BBA','MBA'],minSemester:3,maxSemester:6}, skills:['Market Research','Excel','PowerPoint','Digital Marketing','Canva'], applicationDeadline:deadline(18), startDate:deadline(30), isPPO:false, status:'Open' },
    // ── New 15 ──
    { title:'Machine Learning Intern', company:'Adobe Systems India', description:'Build and evaluate generative AI models for Adobe\'s Creative Cloud suite. Contribute to real shipped features used by millions of creatives worldwide.', requirements:'Python, PyTorch, NLP or Computer Vision fundamentals', location:'Noida', mode:'Hybrid', duration:'6 months', stipend:{amount:50000,currency:'INR',period:'month'}, eligibility:{minCGPA:8.0,allowedCourses:['B.Tech','M.Tech','M.Sc'],minSemester:5,maxSemester:8}, skills:['Python','PyTorch','NLP','Hugging Face','Git'], applicationDeadline:deadline(22), startDate:deadline(40), isPPO:true, status:'Open' },
    { title:'Cloud Engineering Intern', company:'Infosys', description:'Assist cloud migration projects for enterprise clients on AWS. Write Infrastructure-as-Code using Terraform and automate deployments with CI/CD pipelines.', requirements:'Linux basics, AWS fundamentals, Python or Bash scripting', location:'Bengaluru', mode:'On-site', duration:'3 months', stipend:{amount:20000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech','M.Tech','MCA','BCA'],minSemester:3,maxSemester:8}, skills:['AWS','Terraform','Python','Docker','Linux'], applicationDeadline:deadline(28), startDate:deadline(48), isPPO:false, status:'Open' },
    { title:'IoT & Wireless Systems Intern', company:'Qualcomm India', description:'Prototype 5G NR IoT sensor nodes and validate RF performance on Qualcomm dev boards. Document results for product engineering teams.', requirements:'ECE fundamentals, Python, basic RF knowledge', location:'Hyderabad', mode:'On-site', duration:'6 months', stipend:{amount:30000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Tech'],minSemester:5,maxSemester:8}, skills:['Python','RF Design','IoT','Signal Processing','Arduino'], applicationDeadline:deadline(17), startDate:deadline(38), isPPO:true, status:'Open' },
    { title:'Frontend Development Intern', company:'Razorpay', description:'Build responsive React components for Razorpay Dashboard used by 10M+ merchants. Collaborate with designers in Figma and ship pixel-perfect UI.', requirements:'HTML/CSS, React, JavaScript, basic REST API integration', location:'Bengaluru', mode:'Remote', duration:'3 months', stipend:{amount:25000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech','MCA','BCA'],minSemester:3,maxSemester:8}, skills:['React','JavaScript','Tailwind CSS','Figma','Git'], applicationDeadline:deadline(14), startDate:deadline(30), isPPO:false, status:'Open' },
    { title:'Investment Research Intern', company:'HDFC Securities', description:'Compile sector reports, build financial models for mid-cap equities, and prepare weekly market summaries for institutional clients.', requirements:'MBA Finance or CFA Level 1, Excel, financial analysis basics', location:'Mumbai', mode:'On-site', duration:'2 months', stipend:{amount:22000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.5,allowedCourses:['MBA'],minSemester:1,maxSemester:4}, skills:['Excel VBA','Financial Modelling','Bloomberg','PowerPoint'], applicationDeadline:deadline(12), startDate:deadline(28), isPPO:false, status:'Open' },
    { title:'Structural Analysis Intern', company:'DLF Group', description:'Assist senior structural engineers in analysing and detailing RCC and steel structures for high-rise residential projects using ETABS and SAFE.', requirements:'B.Tech Civil, ETABS or STAAD, AutoCAD drafting', location:'New Delhi', mode:'On-site', duration:'3 months', stipend:{amount:12000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.0,allowedCourses:['B.Tech'],minSemester:5,maxSemester:8}, skills:['ETABS','STAAD Pro','AutoCAD','Structural Analysis','MS Excel'], applicationDeadline:deadline(33), startDate:deadline(52), isPPO:false, status:'Open' },
    { title:'HR Analytics Intern', company:'Wipro Technologies', description:'Analyse employee engagement and attrition data using Power BI dashboards. Support HR business partners with workforce planning models.', requirements:'MBA HR, Excel, Power BI or Tableau, basic statistics', location:'Hyderabad', mode:'Hybrid', duration:'3 months', stipend:{amount:18000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['MBA','BBA'],minSemester:1,maxSemester:6}, skills:['Power BI','Excel','HR Analytics','Python','Tableau'], applicationDeadline:deadline(20), startDate:deadline(38), isPPO:false, status:'Open' },
    { title:'Web Development Intern', company:'Zoho Corporation', description:'Develop modules for Zoho\'s suite of SaaS products using React and Node.js. Participate in code reviews and agile sprint ceremonies.', requirements:'JavaScript, React, Node.js basics, understanding of REST APIs', location:'Chennai', mode:'On-site', duration:'6 months', stipend:{amount:22000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['B.Tech','MCA','BCA'],minSemester:3,maxSemester:8}, skills:['React','Node.js','JavaScript','MySQL','Git'], applicationDeadline:deadline(24), startDate:deadline(44), isPPO:true, status:'Open' },
    { title:'Data Analytics Intern', company:'Mu Sigma', description:'Work on client analytics projects spanning retail, healthcare, and financial services. Build dashboards and present insights to business stakeholders.', requirements:'Python or R, SQL, basic statistics, communication skills', location:'Bengaluru', mode:'On-site', duration:'6 months', stipend:{amount:28000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','M.Sc','M.Tech','BCA'],minSemester:3,maxSemester:8}, skills:['Python','SQL','Tableau','Excel','Statistics'], applicationDeadline:deadline(19), startDate:deadline(36), isPPO:true, status:'Open' },
    { title:'Operations & Logistics Intern', company:'Reliance Industries', description:'Assist supply chain planners in demand forecasting, vendor co-ordination, and logistics optimisation across Reliance\'s retail distribution network.', requirements:'BBA/MBA Operations, Excel, basic SAP', location:'Mumbai', mode:'On-site', duration:'6 months', stipend:{amount:16000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['BBA','MBA'],minSemester:3,maxSemester:6}, skills:['SAP','Excel','Supply Chain','Logistics','MS Project'], applicationDeadline:deadline(30), startDate:deadline(50), isPPO:false, status:'Open' },
    { title:'Android Development Intern', company:'PhonePe', description:'Work on feature development for the PhonePe Android app used by 500M+ users. Learn Kotlin, Jetpack Compose, and mobile performance best practices.', requirements:'Kotlin or Java, Android SDK basics, understanding of OOP', location:'Bengaluru', mode:'On-site', duration:'3 months', stipend:{amount:35000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.0,allowedCourses:['B.Tech','MCA','BCA'],minSemester:5,maxSemester:8}, skills:['Kotlin','Android SDK','Jetpack Compose','Git','REST APIs'], applicationDeadline:deadline(16), startDate:deadline(33), isPPO:true, status:'Open' },
    { title:'Pharmaceutical Research Intern', company:"Dr. Reddy's Laboratories", description:'Support analytical chemistry team in method development and validation using HPLC, GC-MS, and UV spectroscopy for Active Pharmaceutical Ingredients.', requirements:'B.Sc/M.Sc Chemistry, HPLC/GC-MS experience, lab safety protocols', location:'Hyderabad', mode:'On-site', duration:'3 months', stipend:{amount:12000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.5,allowedCourses:['B.Sc','M.Sc'],minSemester:3,maxSemester:8}, skills:['HPLC','GC-MS','Spectroscopy','Analytical Chemistry','ICH Guidelines'], applicationDeadline:deadline(27), startDate:deadline(46), isPPO:false, status:'Open' },
    { title:'Computational Physics Intern', company:'TIFR Mumbai', description:'Assist researchers in numerical simulations of quantum many-body systems using Python and C++. Contribute to published research in condensed matter physics.', requirements:'M.Sc Physics, Python, C++ basics, linear algebra, quantum mechanics', location:'Mumbai', mode:'On-site', duration:'6 months', stipend:{amount:14000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.5,allowedCourses:['M.Sc','B.Sc'],minSemester:3,maxSemester:8}, skills:['Python','C++','MATLAB','LaTeX','Quantum Mechanics'], applicationDeadline:deadline(35), startDate:deadline(56), isPPO:false, status:'Open' },
    { title:'Digital Marketing Intern', company:'Nykaa', description:'Assist performance marketing team in managing Meta Ads, Google Ads, and influencer campaigns for beauty and fashion product categories.', requirements:'BBA/MBA Marketing, familiarity with Meta Ads Manager, Excel', location:'Mumbai', mode:'Hybrid', duration:'3 months', stipend:{amount:15000,currency:'INR',period:'month'}, eligibility:{minCGPA:6.0,allowedCourses:['BBA','MBA'],minSemester:3,maxSemester:6}, skills:['Meta Ads','Google Ads','Excel','Canva','Digital Marketing'], applicationDeadline:deadline(21), startDate:deadline(38), isPPO:false, status:'Open' },
    { title:'Business Analyst Intern', company:'Deloitte India', description:'Support consulting engagement teams with data collection, client workshop facilitation, and PowerPoint deliverable preparation for strategy and transformation projects.', requirements:'MBA or B.Tech, strong Excel and PowerPoint, analytical thinking', location:'Mumbai', mode:'On-site', duration:'3 months', stipend:{amount:55000,currency:'INR',period:'month'}, eligibility:{minCGPA:7.5,allowedCourses:['MBA','B.Tech'],minSemester:1,maxSemester:8}, skills:['Excel','PowerPoint','SQL','Consulting','Problem Solving'], applicationDeadline:deadline(13), startDate:deadline(29), isPPO:true, status:'Open' },
  ];

  const createdInternships = await Internship.insertMany(internshipsData.map(i => ({ ...i, postedBy:adminUser._id })));
  console.log(`✅ ${createdInternships.length} Internships created (5 original + 15 new)\n`);

  // ═══════════════════════════════════════
  //  5. APPLICATIONS — for placed/in-process students
  // ═══════════════════════════════════════
  await Application.deleteMany({});

  // Map: student email → job company → status
  const appMap = [
    { email:'aarav.sharma01@gmail.com',     jobIdx:0, status:'Selected' },
    { email:'aarav.sharma01@gmail.com',     jobIdx:2, status:'Rejected' },
    { email:'priya.patel22@gmail.com',      jobIdx:2, status:'Selected' },
    { email:'priya.patel22@gmail.com',      jobIdx:1, status:'Shortlisted' },
    { email:'rohan.verma03@gmail.com',      jobIdx:0, status:'Interview Scheduled' },
    { email:'rohan.verma03@gmail.com',      jobIdx:6, status:'Applied' },
    { email:'sneha.gupta04@gmail.com',      jobIdx:0, status:'Applied' },
    { email:'karan.mehta05@gmail.com',      jobIdx:3, status:'Selected' },
    { email:'divya.singh06@gmail.com',      jobIdx:3, status:'Applied' },
    { email:'arjun.nair07@gmail.com',       jobIdx:9, status:'Selected' },
    { email:'arjun.nair07@gmail.com',       jobIdx:7, status:'Shortlisted' },
    { email:'meera.joshi08@gmail.com',      jobIdx:9, status:'Applied' },
    { email:'yash.kulkarni09@gmail.com',    jobIdx:7, status:'Applied' },
    { email:'swati.jain10@gmail.com',       jobIdx:7, status:'Interview Scheduled' },
    { email:'rahul.iyer11@gmail.com',       jobIdx:1, status:'Selected' },
    { email:'rahul.iyer11@gmail.com',       jobIdx:6, status:'Rejected' },
    { email:'kavya.reddy12@gmail.com',      jobIdx:1, status:'Shortlisted' },
    { email:'ritika.saxena13@gmail.com',    jobIdx:6, status:'Selected' },
    { email:'ritika.saxena13@gmail.com',    jobIdx:1, status:'On Hold' },
    { email:'siddharth.kumar14@gmail.com',  jobIdx:0, status:'Interview Scheduled' },
    { email:'pooja.agarwal15@gmail.com',    jobIdx:0, status:'Applied' },
    { email:'nikhil.chauhan16@gmail.com',   jobIdx:0, status:'Applied' },
    { email:'ananya.mishra17@gmail.com',    jobIdx:2, status:'Selected' },
    { email:'ananya.mishra17@gmail.com',    jobIdx:0, status:'Rejected' },
    { email:'varun.tiwari18@gmail.com',     jobIdx:2, status:'Applied' },
    { email:'ishaan.kapoor19@gmail.com',    jobIdx:8, status:'Selected' },
    { email:'riya.bansal20@gmail.com',      jobIdx:5, status:'Interview Scheduled' },
    { email:'riya.bansal20@gmail.com',      jobIdx:4, status:'Applied' },
    { email:'aditya.rao21@gmail.com',       jobIdx:8, status:'Applied' },
    { email:'manish.trivedi22@gmail.com',   jobIdx:8, status:'Applied' },
    { email:'shruti.malhotra23@gmail.com',  jobIdx:4, status:'Selected' },
    { email:'shruti.malhotra23@gmail.com',  jobIdx:5, status:'Shortlisted' },
    { email:'vivek.saxena24@gmail.com',     jobIdx:8, status:'Applied' },
    { email:'preeti.desai25@gmail.com',     jobIdx:5, status:'Selected' },
    { email:'preeti.desai25@gmail.com',     jobIdx:4, status:'Shortlisted' },
    { email:'nidhi.agrawal29@gmail.com',    jobIdx:6, status:'Selected' },
    { email:'nidhi.agrawal29@gmail.com',    jobIdx:1, status:'Rejected' },
    { email:'tanvi.bose27@gmail.com',       jobIdx:0, status:'Applied' },
    { email:'gaurav.mishra28@gmail.com',    jobIdx:1, status:'Applied' },
    { email:'saurabh.tripathi30@gmail.com', jobIdx:1, status:'Applied' },
  ];

  let appCreated = 0;
  for (const a of appMap) {
    try {
      const user = await User.findOne({ email:a.email });
      if (!user) continue;
      const studentDoc = await Student.findOne({ user:user._id });
      if (!studentDoc) continue;
      const job = createdJobs[a.jobIdx];
      if (!job) continue;
      await Application.create({
        student: studentDoc._id,
        job: job._id,
        status: a.status,
        resumeSnapshot: studentDoc.resume?.path,
        appliedAt: new Date(Date.now() - Math.random()*30*86400000),
      });
      appCreated++;
    } catch(e) { /* skip duplicates */ }
  }
  console.log(`✅ ${appCreated} Applications created\n`);

  // ═══════════════════════════════════════
  //  SUMMARY
  // ═══════════════════════════════════════
  console.log('═'.repeat(65));
  console.log(`  Students  : ${created} created  ${updated} updated`);
  console.log(`  Jobs      : ${createdJobs.length}`);
  console.log(`  Internships: ${createdInternships.length}`);
  console.log(`  Applications: ${appCreated}`);
  console.log('═'.repeat(65));
  console.log(`  Admin login  : admin@placement.edu  /  admin123`);
  console.log(`  Student login: aarav.sharma01@gmail.com  /  student123`);
  console.log(`  All students : password = student123`);
  console.log('═'.repeat(65)+'\n');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch(e => { console.error('❌ Fatal:', e.message); process.exit(1); });
